#app
server:
    port: 8080
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
#    servlet:
#      context-path: /greenhouse
#      session:
#        timeout: 3600s
#    tomcat:
#      uri-encoding: UTF-8
#      context-path: /greenhouse

spring:
#spring热部署
#  devtools:
#    restart:
#      enabled: true
   # Mysql DATABASE CONFIG
  datasource:
    url: jdbc:mysql://localhost:3306/greenhouse?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    logSlowSql: true
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  aop:
      auto: true


#Mybatis-Plus
mybatis-plus:

  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.kuyuntechentity
  global-config:
    id-type: 0
    field-strategy: 0
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#logging
logging:
  level:
    root: info

# 开启MySQL JDBC驱动的日志
# MySQL: DEBUG
